#!/usr/bin/env python3
"""Export canonical process graphs as executable NetworkX builder code.

The generated module contains one function per process plus
``build_all_process_graphs()``.  Graphs are ``nx.MultiDiGraph`` objects so
parallel canonical edges are preserved by ``canonical_edge_id``.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path
from typing import Any

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parents[1]


def _clean(value: Any) -> Any:
    if value is None:
        return None
    if isinstance(value, float) and math.isnan(value):
        return None
    if pd.isna(value):
        return None
    if isinstance(value, str):
        text = value.strip()
        return None if text.lower() in {"", "nan", "none", "null"} else text
    if isinstance(value, (bool, int)):
        return value
    if isinstance(value, float):
        return int(value) if value.is_integer() else value
    return str(value)


def _boolish(value: Any) -> bool:
    text = str(value).strip().lower()
    return text in {"1", "true", "yes", "y"}


def _literal(value: Any) -> str:
    return repr(_clean(value))


def _node_attrs(row: pd.Series) -> dict[str, Any]:
    return {
        "node_id": _clean(row.get("node_id")),
        "node_name": _clean(row.get("node_name")),
        "node_type": _clean(row.get("node_type")),
        "unit_type": _clean(row.get("unit_type")),
        "raw_node_name": _clean(row.get("raw_node_name")),
        "visual_node_name": _clean(row.get("visual_node_name")),
        "is_virtual": _boolish(row.get("is_virtual", False)),
        "mapping_confidence": _clean(row.get("mapping_confidence")),
        "mapping_note": _clean(row.get("mapping_note")),
    }


def _edge_attrs(row: pd.Series, answer_task_by_edge: dict[str, str]) -> dict[str, Any]:
    edge_id = str(row["canonical_edge_id"])
    return {
        "canonical_edge_id": edge_id,
        "src_node": _clean(row.get("src_node")),
        "dst_node": _clean(row.get("dst_node")),
        "src_node_raw": _clean(row.get("src_node_raw")),
        "dst_node_raw": _clean(row.get("dst_node_raw")),
        "visual_stream_id": _clean(row.get("visual_stream_id")),
        "main_data_stream_key": _clean(row.get("main_data_stream_key")),
        "stream_name_norm": _clean(row.get("stream_name_norm")),
        "stream_role": _clean(row.get("stream_role")),
        "is_input_edge": _boolish(row.get("is_input_edge", False)),
        "is_output_edge": _boolish(row.get("is_output_edge", False)),
        "is_internal_edge": _boolish(row.get("is_internal_edge", False)),
        "mapping_confidence": _clean(row.get("mapping_confidence")),
        "mapping_note": _clean(row.get("mapping_note")),
        "is_answer_edge": edge_id in answer_task_by_edge,
        "answer_task_name": answer_task_by_edge.get(edge_id),
    }


def _write_attrs(attrs: dict[str, Any]) -> str:
    parts = [f"{key}={_literal(value)}" for key, value in attrs.items() if value is not None]
    return ", ".join(parts)


def export_networkx_code(
    *,
    reference_dir: Path,
    output_path: Path,
    process_ids: list[int],
) -> None:
    nodes_df = pd.read_csv(reference_dir / "canonical_nodes.csv")
    edges_df = pd.read_csv(reference_dir / "canonical_edges.csv")
    answers_df = pd.read_csv(reference_dir / "target_answer_edges.csv")

    lines: list[str] = [
        "# Auto-generated by scripts/export_process_graph_networkx.py",
        "from __future__ import annotations",
        "",
        "import networkx as nx",
        "",
        "",
    ]

    for pid in process_ids:
        ndf = nodes_df[nodes_df["process_id"].astype(int) == int(pid)].copy()
        edf = edges_df[edges_df["process_id"].astype(int) == int(pid)].copy()
        adf = answers_df[answers_df["process_id"].astype(int) == int(pid)].copy()
        answer_task_by_edge = {
            str(row["canonical_answer_edge_id"]): str(row["task_name"])
            for _, row in adf.iterrows()
        }
        if ndf.empty or edf.empty:
            raise ValueError(f"No canonical graph rows found for process_id={pid}.")

        lines.append(f"def build_process_{pid:02d}_graph() -> nx.MultiDiGraph:")
        lines.append(f"    G = nx.MultiDiGraph(process_id='Process{pid}', process_num={pid})")
        for _, row in ndf.iterrows():
            node_name = str(row["node_name"])
            lines.append(f"    G.add_node({_literal(node_name)}, {_write_attrs(_node_attrs(row))})")
        for _, row in edf.iterrows():
            attrs = _edge_attrs(row, answer_task_by_edge)
            src = str(row["src_node"])
            dst = str(row["dst_node"])
            edge_id = str(row["canonical_edge_id"])
            lines.append(
                f"    G.add_edge({_literal(src)}, {_literal(dst)}, key={_literal(edge_id)}, "
                f"{_write_attrs(attrs)})"
            )
        lines.append("    return G")
        lines.append("")
        lines.append("")

    lines.append("def build_all_process_graphs() -> dict[int, nx.MultiDiGraph]:")
    lines.append("    return {")
    for pid in process_ids:
        lines.append(f"        {pid}: build_process_{pid:02d}_graph(),")
    lines.append("    }")
    lines.append("")
    lines.append("")
    lines.append("PROCESS_GRAPH_BUILDERS = {")
    for pid in process_ids:
        lines.append(f"    {pid}: build_process_{pid:02d}_graph,")
    lines.append("}")
    lines.append("")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Export canonical process graphs as NetworkX builder code.")
    parser.add_argument("--reference-dir", default="data/reference/v3")
    parser.add_argument("--output", default="outputs/process_graph_networkx/process_graphs_networkx.py")
    parser.add_argument("--process-ids", type=int, nargs="+", default=list(range(1, 11)))
    args = parser.parse_args()

    reference_dir = (PROJECT_ROOT / args.reference_dir).resolve()
    output_path = (PROJECT_ROOT / args.output).resolve()
    export_networkx_code(
        reference_dir=reference_dir,
        output_path=output_path,
        process_ids=[int(x) for x in args.process_ids],
    )
    print(f"[networkx-export] wrote {output_path}")


if __name__ == "__main__":
    main()
